#include <StdInc.h>

#include "Commands.hpp"
#include <CommandParser/Parser.hpp>
#include "AudioEngine.h"
#include "FireManager.h"
#include "Timer.h"
#include "Streaming.h"
#include "TheScripts.h"
#include "Conversations.h"
#include "CommandParser/Parser.hpp"

/*!
* Various Script commands
*/

namespace {
void TerminateAllScriptsWithThisName(std::string_view name) {
    const notsa::ci_string_view ciName{ name }; // TODO: Support this natively in the parser
    for (CRunningScript *script = CTheScripts::pActiveScripts, *next; script; script = next) {
        next = script->m_pNext;

        if (script->m_szName == ciName) {
            script->RemoveScriptFromList(&CTheScripts::pActiveScripts);
            script->AddScriptToList(&CTheScripts::pIdleScripts);
            script->ShutdownThisScript();
        }
    }
}

void RemoveAllScriptFires() {
    gFireManager.RemoveAllScriptFires();
}

void LoadScene(CVector point) {
    CTimer::Stop();
    CStreaming::LoadScene(point);
    CTimer::Update();
}

void LoadSceneInDirection(CVector point, float heading) {
    CTimer::Stop();
    CRenderer::RequestObjectsInDirection(point, heading, STREAMING_LOADING_SCENE);
    CStreaming::LoadScene(point);
    CTimer::Update();
}

void LoadMissionAudio(uint32 slotId, int32 sampleId) {
    AudioEngine.PreloadMissionAudio(slotId - 1, sampleId);
}

void AttachMissionAudioToCar(uint32 slotId, CVehicle& veh) {
    AudioEngine.AttachMissionAudioToPhysical(slotId - 1, &veh);
}

void ReportMissionAudioEventAtChar(CPed& ped, int32 eventId) {
    AudioEngine.ReportMissionAudioEvent(eventId, &ped);
}

void ReportMissionAudioEventAtCar(CVehicle& vehicle, int eventId) {
    AudioEngine.ReportMissionAudioEvent(eventId, &vehicle);
}

void PlayMissionAudio(uint32 slotId) {
    AudioEngine.PlayLoadedMissionAudio(slotId - 1);
}

void SetPhotoCameraEffect(bool enable) {
    CTheScripts::bDrawCrossHair = enable ? eCrossHairType::FIXED_DRAW_1STPERSON_WEAPON : eCrossHairType::NONE;
}

void DrawOddJobTitleBeforeFade(bool enable) {
    CTheScripts::bDrawOddJobTitleBeforeFade = enable;
}

void DrawSubtitlesBeforeFade(bool enable) {
    CTheScripts::bDrawSubtitlesBeforeFade = enable;
}

void SetPlayerInStadium(bool enable) {
    CTheScripts::bPlayerIsOffTheMap = enable;
}

};

void notsa::script::commands::script::RegisterHandlers() {
    REGISTER_COMMAND_HANDLER_BEGIN("Script");

    REGISTER_COMMAND_HANDLER(COMMAND_TERMINATE_ALL_SCRIPTS_WITH_THIS_NAME, TerminateAllScriptsWithThisName);
    REGISTER_COMMAND_HANDLER(COMMAND_REMOVE_ALL_SCRIPT_FIRES, RemoveAllScriptFires);
    REGISTER_COMMAND_HANDLER(COMMAND_LOAD_SCENE, LoadScene);
    REGISTER_COMMAND_HANDLER(COMMAND_LOAD_SCENE_IN_DIRECTION, LoadSceneInDirection);
    REGISTER_COMMAND_HANDLER(COMMAND_LOAD_MISSION_AUDIO, LoadMissionAudio);
    REGISTER_COMMAND_HANDLER(COMMAND_ATTACH_MISSION_AUDIO_TO_CAR, AttachMissionAudioToCar);
    REGISTER_COMMAND_HANDLER(COMMAND_REPORT_MISSION_AUDIO_EVENT_AT_CHAR, ReportMissionAudioEventAtChar);
    REGISTER_COMMAND_HANDLER(COMMAND_REPORT_MISSION_AUDIO_EVENT_AT_CAR, ReportMissionAudioEventAtCar);
    REGISTER_COMMAND_HANDLER(COMMAND_PLAY_MISSION_AUDIO, PlayMissionAudio);
    REGISTER_COMMAND_HANDLER(COMMAND_SET_PHOTO_CAMERA_EFFECT, SetPhotoCameraEffect);
    REGISTER_COMMAND_HANDLER(COMMAND_DRAW_ODDJOB_TITLE_BEFORE_FADE, DrawOddJobTitleBeforeFade);
    REGISTER_COMMAND_HANDLER(COMMAND_DRAW_SUBTITLES_BEFORE_FADE, DrawSubtitlesBeforeFade);
    REGISTER_COMMAND_HANDLER(COMMAND_SET_PLAYER_IS_IN_STADIUM, SetPlayerInStadium);


    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ACTIVATE_CRANE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_BLIP_FOR_CONTACT_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_BLOOD_RING_KILLS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_GARBAGE_PICKUPS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_ICE_CREAMS_SOLD);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_LOAN_SHARK_VISITS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_SPENT_ON_AUTO_PAINTING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_SPENT_ON_CLOTHES);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_SPENT_ON_GAMBLING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_SPENT_ON_PROPERTY);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_SPENT_ON_WEAPONS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MONEY_WON_ON_GAMBLING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_MOVIE_STUNTS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_NUMBER_OF_ASSASSINATIONS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_PAGER_MESSAGE_WITH_NUMBER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_PIZZAS_DELIVERED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_PORN_LEAFLET_TO_RUBBISH);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_ROUTE_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_SHOOTING_RANGE_RANK);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_SHORT_RANGE_BLIP_FOR_CONTACT_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_SHORT_RANGE_BLIP_FOR_COORD);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_SHORT_RANGE_BLIP_FOR_COORD_OLD);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_SPRITE_BLIP_FOR_PICKUP);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ADD_STORES_KNOCKED_OFF);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_ARM_CAR_WITH_BOMB);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_BLOCK_NODES_IN_AREA);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CHANGE_BLIP_THRESHOLD);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CHANGE_GARAGE_TYPE_WITH_CAR_MODEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CLEAR_THREAT_FOR_PED_TYPE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CLOSE_CAR_BOOT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CLOSE_FRIEND_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CLOSE_THREAT_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CREATE_DUST_EFFECT_FOR_CUTSCENE_HELI);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CREATE_PED_GENERATOR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_CREATE_SINGLE_PARTICLE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DEACTIVATE_CRANE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DECLARE_BASE_BRIEF_ID_FOR_CONTACT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DECLARE_MISSION_FLAG_FOR_CONTACT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DESTROY_PROJECTILES_IN_AREA);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DIM_BLIP);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DISARM_CHAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DISPLAY_NTH_ONSCREEN_COUNTER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DOES_GARAGE_CONTAIN_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DONT_REMOVE_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DO_2D_LINES_INTERSECT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_DRAW_DEBUG_CUBE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FIND_DRUG_PLANE_COORDINATES);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FIND_NEAREST_MULTIBUILDING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FLASH_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FLASH_CHAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FORCE_RAIN);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FREEZE_OBJECT_POSITION_AND_DONT_LOAD_COLLISION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_FREEZE_STATE_OF_INTERIORS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_BODY_CAST_HEALTH);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_CHASE_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_CLOSEST_CAR_NODE_WITH_HEADING_AWAY_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_CLOSEST_CAR_NODE_WITH_HEADING_TOWARDS_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_CLOSEST_WATER_NODE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_FIRST_PICKUP_COORDS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_MULTIBUILDING_MODEL_INDEX);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_NEAREST_TYRE_TO_POINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_NEXT_PICKUP_COORDS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_NUMBER_MULTIBUILDING_MODELS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_NUMBER_OF_SEATS_IN_MODEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_NUMBER_OF_SONY_CDS_READ);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_OBJECT_DISTANCE_ALONG_PATH);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_PATROL_ALERTNESS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GET_RANDOM_ICE_CREAM_CUSTOMER_IN_AREA);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GIVE_WEAPON_TO_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GOSUB_FILE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_GRAB_PHONE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_HAS_MILITARY_CRANE_COLLECTED_ALL_CARS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_HAS_PHONE_DISPLAYED_MESSAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_HAS_PHOTOGRAPH_BEEN_TAKEN);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_HAS_SONY_CD_BEEN_READ);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_ARMED_WITH_ANY_BOMB);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_ARMED_WITH_BOMB);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_DOOR_CLOSED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_DROWNING_IN_WATER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_IN_ANGLED_AREA_2D);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_IN_ANGLED_AREA_3D);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_IN_MISSION_GARAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_CAR_STILL_ALIVE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_FLOAT_LVAR_NOT_EQUAL_TO_FLOAT_VAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_INT_LVAR_NOT_EQUAL_TO_INT_VAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_ITALIAN_GAME);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_MISSION_AUDIO_LOADING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_MISSION_AUDIO_PLAYING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_OBJECT_WAITING_FOR_WORLD_COLLISION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_REPLAY_PLAYING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_SPANISH_GAME);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_IS_THREAT_FOR_PED_TYPE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_KILL_CHAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_LEAVE_GROUP);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_LOAD_COLLISION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_LOAD_COLLISION_WITH_SCREEN);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_LOCATE_SNIPER_BULLET_2D);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_LOCATE_SNIPER_BULLET_3D);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_MAKE_CRAIGS_CAR_A_BIT_STRONGER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_MARK_PED_ROADS_BETWEEN_LEVELS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_MARK_ROADS_BETWEEN_LEVELS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_OPEN_FRIEND_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_OPEN_THREAT_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_OVERRIDE_HOSPITAL_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_OVERRIDE_POLICE_STATION_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_PERFORM_SEQUENCE_TASK_REPEATEDLY);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_PLACE_OBJECT_RELATIVE_TO_OBJECT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_PRINT_SOON);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_AMBULANCE_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_CRIMINAL_CAUGHT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_FIRE_EXTINGUISHED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_FIRE_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_JUMP_FLIPS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_KILL_FRENZY_PASSED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_LIFE_SAVED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_LONGEST_DODO_FLIGHT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REGISTER_VIGILANTE_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REMOVE_CAR_FROM_CHASE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REMOVE_FRIEND_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REMOVE_THREAT_LIST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_REPLAY);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_RESTART_CRITICAL_MISSION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_RESTORE_WEATHER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SAVE_VAR_FLOAT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SAVE_VAR_INT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_ALERTNESS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_ALLOW_HURRICANES);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_ALL_OCCUPANTS_OF_CAR_LEAVE_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_ALL_TAXI_LIGHTS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_DRIVE_STRAIGHT_AHEAD);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_HANDBRAKE_STOP);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_HANDBRAKE_TURN_RIGHT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_IGNORE_LEVEL_TRANSITIONS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_STAYS_IN_CURRENT_LEVEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CAR_WAIT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CHARS_CHATTING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CHAR_OBJ_GOTO_CAR_ON_FOOT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CHAR_OBJ_STEAL_ANY_CAR_EVEN_MISSION_CAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CURRENT_BUYABLE_PROPERTY);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_CURRENT_CAR_WEAPON);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_FADE_AND_JUMPCUT_AFTER_RC_EXPLOSION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_FADE_IN_AFTER_NEXT_ARREST);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_FADE_IN_AFTER_NEXT_DEATH);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_FREE_BOMBS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GANG_ATTITUDE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GANG_GANG_ATTITUDE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GANG_PED_MODEL_PREFERENCE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GARAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GARAGE_WITH_CAR_MODEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GET_OUT_OF_JAIL_FREE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GLOBAL_PED_SEARCH_PARAMS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GROUP_DEFAULT_LEADER_TASK);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_GROUP_DEFAULT_TASK);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_INTRO_IS_PLAYING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_LARGEST_GAMBLING_WIN);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_LOAD_COLLISION_FOR_OBJECT_FLAG);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_LONGEST_TIME_IN_BLOOD_RING);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_MAXIMUM_NUMBER_OF_CARS_IN_GARAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_MULTIBUILDING_MODEL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PEDMODEL_AS_FRIEND);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PEDMODEL_AS_THREAT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PEDTYPE_AS_FRIEND);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PEDTYPE_AS_THREAT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PHONE_MESSAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_POWERPOINT);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_PROPERTY_AS_OWNED);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_REPEATED_PHONE_MESSAGE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_SCRIPT_FIRE_AUDIO);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_SCRIPT_POLICE_HELI_TO_CHASE_CHAR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_THREAT_FOR_PED_TYPE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_TOP_SHOOTING_RANGE_SCORE);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SET_TOTAL_NUMBER_OF_KILL_FRENZIES);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_START_BOAT_FOAM_ANIMATION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_START_OBJECT_ON_PATH);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_STORE_WEATHER);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SWITCH_PED_GENERATOR);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_SWITCH_VEHICLE_WEAPONS);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_TASK_GO_ON_PATROL);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_TURN_PHONE_OFF);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_TURN_PHONE_ON);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_UPDATE_BOAT_FOAM_ANIMATION);
    REGISTER_COMMAND_UNIMPLEMENTED(COMMAND_WAS_VEHICLE_EVER_POLICE);
}
