#pragma once

/*
* SfxIDs (Sound IDs) in sound banks
*/

using eSoundID = int16;

enum SND_GENRL_WEAPONS : eSoundID {               // GENRL_WEAPONS
    SND_GENRL_WEAPONS_UNK                   = -1, // 1
    SND_GENRL_WEAPONS_9MM1SHOT_L            = 0,  // 0x0
    SND_GENRL_WEAPONS_9MM1SHOT_R            = 1,  // 0x1
    SND_GENRL_WEAPONS_9MM1TAIL              = 2,  // 0x2
    SND_GENRL_WEAPONS_AK_SHOT_L             = 3,  // 0x3
    SND_GENRL_WEAPONS_AK_SHOT_R             = 4,  // 0x4
    SND_GENRL_WEAPONS_AK_TAIL_L             = 5,  // 0x5
    SND_GENRL_WEAPONS_EAGLE_SHOT_L          = 6,  // 0x6
    SND_GENRL_WEAPONS_EAGLE_SHOT_R          = 7,  // 0x7
    SND_GENRL_WEAPONS_EAGLE_TAIL_L          = 8,  // 0x8
    SND_GENRL_WEAPONS_FIRE_EXT              = 9,  // 0x9
    SND_GENRL_WEAPONS_GAS_LOOP              = 10, // 0xA
    SND_GENRL_WEAPONS_MINIGUN_SHOT_L        = 11, // 0xB
    SND_GENRL_WEAPONS_MINIGUN_SHOT_R        = 12, // 0xC
    SND_GENRL_WEAPONS_MINIGUN_TAIL          = 13, // 0xD
    SND_GENRL_WEAPONS_MINIGUNEMPTY          = 14, // 0xE
    SND_GENRL_WEAPONS_MINIGUNHIGHS          = 15, // 0xF
    SND_GENRL_WEAPONS_MINIGUNLOWS           = 16, // 0x10
    SND_GENRL_WEAPONS_MP5SHOT_L             = 17, // 0x11
    SND_GENRL_WEAPONS_MP5SHOT_R             = 18, // 0x12
    SND_GENRL_WEAPONS_PARACHUTE_WIND_LOOP_A = 19, // 0x13
    SND_GENRL_WEAPONS_PARACHUTE_WIND_LOOP_B = 20, // 0x14
    SND_GENRL_WEAPONS_SHOTGUN_SHOT_L        = 21, // 0x15
    SND_GENRL_WEAPONS_SHOTGUN_SHOT_R        = 22, // 0x16
    SND_GENRL_WEAPONS_SHOTGUN_TAIL_R        = 23, // 0x17
    SND_GENRL_WEAPONS_SILENCED_SHOT_L       = 24, // 0x18
    SND_GENRL_WEAPONS_SILENCED_SHOT_R       = 25, // 0x19
    SND_GENRL_WEAPONS_SNIPER_SHOT_L         = 26, // 0x1A
    SND_GENRL_WEAPONS_SNIPER_SHOT_R         = 27, // 0x1B
    SND_GENRL_WEAPONS_SPRAY_PAINT           = 28, // 0x1C
    SND_GENRL_WEAPONS_9MM1DRY               = 29, // 0x1D
    SND_GENRL_WEAPONS_9MM1LOWS              = 30, // 0x1E
    SND_GENRL_WEAPONS_AK_A                  = 31, // 0x1F
    SND_GENRL_WEAPONS_AK_B                  = 32, // 0x20
    SND_GENRL_WEAPONS_AK_DRYFIRE            = 33, // 0x21
    SND_GENRL_WEAPONS_BASEBALL_BAT          = 34, // 0x22
    SND_GENRL_WEAPONS_BAT_STRIKE            = 35, // 0x23
    SND_GENRL_WEAPONS_BODY_PUNCH1           = 36, // 0x24
    SND_GENRL_WEAPONS_BODY_PUNCH2           = 37, // 0x25
    SND_GENRL_WEAPONS_BODY_PUNCH3           = 38, // 0x26
    SND_GENRL_WEAPONS_BODY_PUNCH4           = 39, // 0x27
    SND_GENRL_WEAPONS_BOX_FACE1             = 40, // 0x28
    SND_GENRL_WEAPONS_BOX_FACE2             = 41, // 0x29
    SND_GENRL_WEAPONS_BOX_FACE3             = 42, // 0x2A
    SND_GENRL_WEAPONS_BOX_FACE4             = 43, // 0x2B
    SND_GENRL_WEAPONS_BRASS_KNUCKLES        = 44, // 0x2C
    SND_GENRL_WEAPONS_CAMERA                = 45, // 0x2D
    SND_GENRL_WEAPONS_CANE_STRIKE           = 46, // 0x2E
    SND_GENRL_WEAPONS_CANE_SWISH            = 47, // 0x2F
    SND_GENRL_WEAPONS_CLUB_STRIKE           = 48, // 0x30
    SND_GENRL_WEAPONS_DETONATOR_BEEP        = 49, // 0x31
    SND_GENRL_WEAPONS_DILDO                 = 50, // 0x32
    SND_GENRL_WEAPONS_EAGLE_B               = 51, // 0x33
    SND_GENRL_WEAPONS_EAGLE_DRYFIRE         = 52, // 0x34
    SND_GENRL_WEAPONS_EAGLE_LOWS            = 53, // 0x35
    SND_GENRL_WEAPONS_FLOWER_STRIKE         = 54, // 0x36
    SND_GENRL_WEAPONS_HANDGUN_A             = 55, // 0x37
    SND_GENRL_WEAPONS_KATANA_SWORD          = 56, // 0x38
    SND_GENRL_WEAPONS_KNIFE                 = 57, // 0x39
    SND_GENRL_WEAPONS_KNUCKLE               = 58, // 0x3A
    SND_GENRL_WEAPONS_MARTIAL_STRIKE1       = 59, // 0x3B
    SND_GENRL_WEAPONS_MARTIAL_STRIKE2       = 60, // 0x3C
    SND_GENRL_WEAPONS_MARTIAL_STRIKE3       = 61, // 0x3D
    SND_GENRL_WEAPONS_MARTIAL_STRIKE4       = 62, // 0x3E
    SND_GENRL_WEAPONS_MINIGUNOFF            = 63, // 0x3F
    SND_GENRL_WEAPONS_NIGHT_VISION          = 64, // 0x40
    SND_GENRL_WEAPONS_PARACHUTE_OPEN        = 65, // 0x41
    SND_GENRL_WEAPONS_PISTOL_B              = 66, // 0x42
    SND_GENRL_WEAPONS_POOLCUE               = 67, // 0x43
    SND_GENRL_WEAPONS_ROCKET_LAUNCH         = 68, // 0x44
    SND_GENRL_WEAPONS_SAWNOFF_A             = 69, // 0x45
    SND_GENRL_WEAPONS_SAWNOFF_B             = 70, // 0x46
    SND_GENRL_WEAPONS_SHOTGUN_A             = 71, // 0x47
    SND_GENRL_WEAPONS_SHOTGUN_B             = 72, // 0x48
    SND_GENRL_WEAPONS_SHOTGUN_DRYFIRE       = 73, // 0x49
    SND_GENRL_WEAPONS_SHOTGUN_LOWS          = 74, // 0x4A
    SND_GENRL_WEAPONS_SHOVEL                = 75, // 0x4B
    SND_GENRL_WEAPONS_SILENCED_DRYFIRE      = 76, // 0x4C
    SND_GENRL_WEAPONS_SILENCED_LOWS         = 77, // 0x4D
    SND_GENRL_WEAPONS_SMACK_1               = 78, // 0x4E
    SND_GENRL_WEAPONS_SMACK_2               = 79, // 0x4F
    SND_GENRL_WEAPONS_SMACK_3               = 80, // 0x50
    SND_GENRL_WEAPONS_STAB                  = 81, // 0x51
    SND_GENRL_WEAPONS_STOMP1                = 82, // 0x52
    SND_GENRL_WEAPONS_TRIGGER               = 83, // 0x53
    SND_GENRL_WEAPONS_UZI_A                 = 84, // 0x54
    SND_GENRL_WEAPONS_UZI_B                 = 85, // 0x55
    SND_GENRL_WEAPONS_WEAPON_SWIPE          = 86, // 0x56
    SND_GENRL_WEAPONS_WEAPON_SWIPE_FIST     = 87, // 0x57
    SND_GENRL_WEAPONS_WEAPON_SWIPE_METAL    = 88, // 0x58
};

enum SND_GENRL_HORN : eSoundID {     // SND_BANK_GENRL_HORN
    SND_GENRL_HORN_BIKEBELL    = 0,  // 0x0
    SND_GENRL_HORN_ESCORTHORN  = 1,  // 0x1
    SND_GENRL_HORN_HORN56CHEV  = 2,  // 0x2
    SND_GENRL_HORN_HORNBMW328  = 3,  // 0x3
    SND_GENRL_HORN_HORNBUS     = 4,  // 0x4
    SND_GENRL_HORN_HORNBUS2    = 5,  // 0x5
    SND_GENRL_HORN_HORNJEEP    = 6,  // 0x6
    SND_GENRL_HORN_HORNPICKUP  = 7,  // 0x7
    SND_GENRL_HORN_HORNPORSCHE = 8,  // 0x8
    SND_GENRL_HORN_HORNTRUCK   = 9,  // 0x9
    SND_GENRL_HORN_SIREN_LONG  = 10, // 0xA
    SND_GENRL_HORN_SIREN_SHORT = 11, // 0xB
    SND_GENRL_HORN_FOGHORN     = 12, // 0xC
    SND_GENRL_HORN_GOODFOGHORN = 13, // 0xD
};

enum SND_GENRL_COLLISIONS : eSoundID {
    SND_GENRL_COLLISIONS_GRASS_SKID       = 0x0,
    SND_GENRL_COLLISIONS_GRAVEL_SKID      = 0x1,
    SND_GENRL_COLLISIONS_METAL_SCRAPE     = 0x2,
    SND_GENRL_COLLISIONS_WATER_LOOP       = 0x3,
    SND_GENRL_COLLISIONS_BARREL_CONE      = 0x4,
    SND_GENRL_COLLISIONS_BIKE_CRASH1      = 0x5,
    SND_GENRL_COLLISIONS_BIKE_CRASH2      = 0x6,
    SND_GENRL_COLLISIONS_BIKE_CRASH3      = 0x7,
    SND_GENRL_COLLISIONS_BIKE_CRASH4      = 0x8,
    SND_GENRL_COLLISIONS_BIKE_CRASH5      = 0x9,
    SND_GENRL_COLLISIONS_BIN_BAG          = 0xA,
    SND_GENRL_COLLISIONS_BOTTLE_SMASH     = 0xB,
    SND_GENRL_COLLISIONS_CARDBOARD_BOX1   = 0xC,
    SND_GENRL_COLLISIONS_CARDBOARD_BOX2   = 0xD,
    SND_GENRL_COLLISIONS_CARDBOARD_BOX3   = 0xE,
    SND_GENRL_COLLISIONS_COL_GLASS_TINK1  = 0xF,
    SND_GENRL_COLLISIONS_COL_GLASS_TINK2  = 0x10,
    SND_GENRL_COLLISIONS_COL_GLASS_TINK3  = 0x11,
    SND_GENRL_COLLISIONS_COL_GLASS_TINK4  = 0x12,
    SND_GENRL_COLLISIONS_COLBENCH1        = 0x13,
    SND_GENRL_COLLISIONS_COLCAR01         = 0x14,
    SND_GENRL_COLLISIONS_COLCAR03         = 0x15,
    SND_GENRL_COLLISIONS_COLCAR04         = 0x16,
    SND_GENRL_COLLISIONS_COLCAR05         = 0x17,
    SND_GENRL_COLLISIONS_COLCAR06         = 0x18,
    SND_GENRL_COLLISIONS_COLCAR08         = 0x19,
    SND_GENRL_COLLISIONS_COLCAR09         = 0x1A,
    SND_GENRL_COLLISIONS_COLCAR10         = 0x1B,
    SND_GENRL_COLLISIONS_COLCAR12         = 0x1C,
    SND_GENRL_COLLISIONS_COLCARPED        = 0x1D,
    SND_GENRL_COLLISIONS_COLCONTAINER     = 0x1E,
    SND_GENRL_COLLISIONS_COLGRASS         = 0x1F,
    SND_GENRL_COLLISIONS_COLLAMPPOST      = 0x20,
    SND_GENRL_COLLISIONS_COLSOLIDWOOD     = 0x21,
    SND_GENRL_COLLISIONS_CONCRETE         = 0x22,
    SND_GENRL_COLLISIONS_CRATE1           = 0x23,
    SND_GENRL_COLLISIONS_CRATE2           = 0x24,
    SND_GENRL_COLLISIONS_CRATE3           = 0x25,
    SND_GENRL_COLLISIONS_DISPENSER        = 0x26,
    SND_GENRL_COLLISIONS_DUMPSTER         = 0x27,
    SND_GENRL_COLLISIONS_FENCE_HEAVY      = 0x28,
    SND_GENRL_COLLISIONS_FENCE_PARTICLES1 = 0x29,
    SND_GENRL_COLLISIONS_FENCE_PARTICLES2 = 0x2A,
    SND_GENRL_COLLISIONS_FENCE_PARTICLES3 = 0x2B,
    SND_GENRL_COLLISIONS_FENCE_PARTICLES4 = 0x2C,
    SND_GENRL_COLLISIONS_FENCE_THIN       = 0x2D,
    SND_GENRL_COLLISIONS_GARAGE_DOOR      = 0x2E,
    SND_GENRL_COLLISIONS_GORE_SPLAT1      = 0x2F,
    SND_GENRL_COLLISIONS_GORE_SPLAT2      = 0x30,
    SND_GENRL_COLLISIONS_GORE_SPLAT3      = 0x31,
    SND_GENRL_COLLISIONS_GRENADE          = 0x32,
    SND_GENRL_COLLISIONS_HARD_GLASS       = 0x33,
    SND_GENRL_COLLISIONS_HAY_BALE         = 0x34,
    SND_GENRL_COLLISIONS_HEADLIGHT        = 0x35,
    SND_GENRL_COLLISIONS_HYDRANT          = 0x36,
    SND_GENRL_COLLISIONS_METAL_BARREL     = 0x37,
    SND_GENRL_COLLISIONS_PANE_BREAK       = 0x38,
    SND_GENRL_COLLISIONS_RIMHIT           = 0x39,
    SND_GENRL_COLLISIONS_RIMSCRAPE        = 0x3A,
    SND_GENRL_COLLISIONS_ROADCONE         = 0x3B,
    SND_GENRL_COLLISIONS_RUBBER           = 0x3C,
    SND_GENRL_COLLISIONS_SATCHEL_CHARGE   = 0x3D,
    SND_GENRL_COLLISIONS_SCAFFOLD_TIGHT   = 0x3E,
    SND_GENRL_COLLISIONS_SIGN_A           = 0x3F,
    SND_GENRL_COLLISIONS_SIGN_B           = 0x40,
    SND_GENRL_COLLISIONS_SOLID_METAL      = 0x41,
    SND_GENRL_COLLISIONS_SPLASH_END       = 0x42,
    SND_GENRL_COLLISIONS_SPLASH_START     = 0x43,
    SND_GENRL_COLLISIONS_WINDSCREEN       = 0x44,
    SND_GENRL_COLLISIONS_WIRE_FENCE1      = 0x45,
    SND_GENRL_COLLISIONS_WIRE_FENCE2      = 0x46,
    SND_GENRL_COLLISIONS_WIRE_FENCE3      = 0x47,
};

enum SND_GENRL_BULLET_HITS : eSoundID {
    SND_GENRL_BULLET_HITS_BLOWOUT        = 0x0,
    SND_GENRL_BULLET_HITS_BULDIR01       = 0x1,
    SND_GENRL_BULLET_HITS_BULDIR02       = 0x2,
    SND_GENRL_BULLET_HITS_BULDIR03       = 0x3,
    SND_GENRL_BULLET_HITS_BULIMT1L       = 0x4,
    SND_GENRL_BULLET_HITS_BULIMT2L       = 0x5,
    SND_GENRL_BULLET_HITS_BULIMT3L       = 0x6,
    SND_GENRL_BULLET_HITS_BULPED1L       = 0x7,
    SND_GENRL_BULLET_HITS_BULPED2L       = 0x8,
    SND_GENRL_BULLET_HITS_BULPED3L       = 0x9,
    SND_GENRL_BULLET_HITS_BULRMT1L       = 0xA,
    SND_GENRL_BULLET_HITS_BULRMT2L       = 0xB,
    SND_GENRL_BULLET_HITS_BULRMT3L       = 0xC,
    SND_GENRL_BULLET_HITS_BULWAL1L       = 0xD,
    SND_GENRL_BULLET_HITS_BULWAL2L       = 0xE,
    SND_GENRL_BULLET_HITS_BULWAL3L       = 0xF,
    SND_GENRL_BULLET_HITS_BULWAT01       = 0x10,
    SND_GENRL_BULLET_HITS_BULWAT02       = 0x11,
    SND_GENRL_BULLET_HITS_BULWAT03       = 0x12,
    SND_GENRL_BULLET_HITS_BULWOD1L       = 0x13,
    SND_GENRL_BULLET_HITS_BULWOD2L       = 0x14,
    SND_GENRL_BULLET_HITS_BULWOD3L       = 0x15,
    SND_GENRL_BULLET_HITS_SHELL_TARMAC_1 = 0x16,
    SND_GENRL_BULLET_HITS_SHELL_TARMAC_2 = 0x17,
};

enum SND_GENRL_DOORS_GARAG : eSoundID {
    SND_GENRL_DOORS_GARAGE_DOOR_LOOP   = 0x0,
    SND_GENRL_DOORS_DOOR_OPEN          = 0x1,
    SND_GENRL_DOORS_GARAGE_DOOR_LIMITS = 0x2,
};

enum SND_GENRL_EXPLOSIONS : eSoundID {
    SND_GENRL_EXPLOSIONS_FIRE_LOOP = 0x0,
    SND_GENRL_EXPLOSIONS_DISTANT_L = 0x1,
    SND_GENRL_EXPLOSIONS_LOWBEE_L  = 0x2,
    SND_GENRL_EXPLOSIONS_MAIN_L    = 0x3,
    SND_GENRL_EXPLOSIONS_NEAR_L    = 0x4,
};

enum SND_GENRL_VEHICLE_GEN : eSoundID {
    SND_GENRL_VEHICLE_GEN_BIKE_SKID_A          = 0x0,
    SND_GENRL_VEHICLE_GEN_BIKE_SKID_B          = 0x1,
    SND_GENRL_VEHICLE_GEN_BROKEN_ENGINE        = 0x2,
    SND_GENRL_VEHICLE_GEN_DISTANT              = 0x3,
    SND_GENRL_VEHICLE_GEN_FLATTIRELP           = 0x4,
    SND_GENRL_VEHICLE_GEN_FRONT_ROTOR          = 0x5,
    SND_GENRL_VEHICLE_GEN_GRASS_SKID_A         = 0x6,
    SND_GENRL_VEHICLE_GEN_GRASS_SKID_B         = 0x7,
    SND_GENRL_VEHICLE_GEN_GRAVEL_SKID_A        = 0x8,
    SND_GENRL_VEHICLE_GEN_GRAVEL_SKID_B        = 0x9,
    SND_GENRL_VEHICLE_GEN_HARRIER_FRONT        = 0xA,
    SND_GENRL_VEHICLE_GEN_HARRIER_REAR         = 0xB,
    SND_GENRL_VEHICLE_GEN_HOOD_FLY             = 0xC,
    SND_GENRL_VEHICLE_GEN_HUMLP                = 0xD,
    SND_GENRL_VEHICLE_GEN_JET_DIST             = 0xE,
    SND_GENRL_VEHICLE_GEN_LIFT_LOOP            = 0xF,
    SND_GENRL_VEHICLE_GEN_PROP_DIST            = 0x10,
    SND_GENRL_VEHICLE_GEN_PROP_NEAR            = 0x11,
    SND_GENRL_VEHICLE_GEN_REAR_ROTOR           = 0x12,
    SND_GENRL_VEHICLE_GEN_REVERSE              = 0x13,
    SND_GENRL_VEHICLE_GEN_REVERSE2             = 0x14,
    SND_GENRL_VEHICLE_GEN_ROAD                 = 0x15,
    SND_GENRL_VEHICLE_GEN_RUMBLE               = 0x16,
    SND_GENRL_VEHICLE_GEN_TAIL_ROTOR           = 0x17,
    SND_GENRL_VEHICLE_GEN_TARSKIDTWIN1         = 0x18,
    SND_GENRL_VEHICLE_GEN_TARSKIDTWIN2         = 0x19,
    SND_GENRL_VEHICLE_GEN_THRUST               = 0x1A,
    SND_GENRL_VEHICLE_GEN_TURRET_LOOP          = 0x1B,
    SND_GENRL_VEHICLE_GEN_UNDERWATER_BOAT_LOOP = 0x1C,
    SND_GENRL_VEHICLE_GEN_WHINE                = 0x1D,
    SND_GENRL_VEHICLE_GEN_BLADE                = 0x1E,
    SND_GENRL_VEHICLE_GEN_BOUNCE_SUSPENSION    = 0x1F,
    SND_GENRL_VEHICLE_GEN_CLLIGHT              = 0x20,
    SND_GENRL_VEHICLE_GEN_CLNEW                = 0x21,
    SND_GENRL_VEHICLE_GEN_CLOLD                = 0x22,
    SND_GENRL_VEHICLE_GEN_CLVAN                = 0x23,
    SND_GENRL_VEHICLE_GEN_CTRUCK               = 0x24,
    SND_GENRL_VEHICLE_GEN_GENERIC_START        = 0x25,
    SND_GENRL_VEHICLE_GEN_HYDRAULIC_SUSPENSION = 0x26,
    SND_GENRL_VEHICLE_GEN_OPLIGHT              = 0x27,
    SND_GENRL_VEHICLE_GEN_OPNEW                = 0x28,
    SND_GENRL_VEHICLE_GEN_OPOLD                = 0x29,
    SND_GENRL_VEHICLE_GEN_OPVAN                = 0x2A,
    SND_GENRL_VEHICLE_GEN_OTRUCK               = 0x2B,
    SND_GENRL_VEHICLE_GEN_TRIGGER_SUSPENSION   = 0x2C,
};

enum SND_GENRL_FRONTEND_GAME : eSoundID {
    SND_GENRL_FRONTEND_GAME_CITY_NOISE_L       = 0x0,
    SND_GENRL_FRONTEND_GAME_RADIOTUNELONG      = 0x1,
    SND_GENRL_FRONTEND_GAME_RADIOTUNESHORT     = 0x2,
    SND_GENRL_FRONTEND_GAME_SCANNER_NOISE_LOOP = 0x3,
    SND_GENRL_FRONTEND_GAME_TIMERL             = 0x4,
    SND_GENRL_FRONTEND_GAME_TIMERR             = 0x5,
    SND_GENRL_FRONTEND_GAME_321L               = 0x6,
    SND_GENRL_FRONTEND_GAME_321R               = 0x7,
    SND_GENRL_FRONTEND_GAME_AMPFIX             = 0x8,
    SND_GENRL_FRONTEND_GAME_BUYCARMOD          = 0x9,
    SND_GENRL_FRONTEND_GAME_DRYAK47            = 0xA,
    SND_GENRL_FRONTEND_GAME_DRYUZI             = 0xB,
    SND_GENRL_FRONTEND_GAME_GOL                = 0xC,
    SND_GENRL_FRONTEND_GAME_GOR                = 0xD,
    SND_GENRL_FRONTEND_GAME_INFOL              = 0xE,
    SND_GENRL_FRONTEND_GAME_INFOR              = 0xF,
    SND_GENRL_FRONTEND_GAME_MONEYL             = 0x10,
    SND_GENRL_FRONTEND_GAME_MONEYR             = 0x11,
    SND_GENRL_FRONTEND_GAME_PARTMISSIONL       = 0x12,
    SND_GENRL_FRONTEND_GAME_PARTMISSIONR       = 0x13,
    SND_GENRL_FRONTEND_GAME_PICKUP_AMMO1       = 0x14,
    SND_GENRL_FRONTEND_GAME_PICKUP_AMMO2       = 0x15,
    SND_GENRL_FRONTEND_GAME_PICKUP_AMMO3       = 0x16,
    SND_GENRL_FRONTEND_GAME_RADIOCLICK         = 0x17,
    SND_GENRL_FRONTEND_GAME_SCANNER_CLICK      = 0x18,
    SND_GENRL_FRONTEND_GAME_STARTL             = 0x19,
    SND_GENRL_FRONTEND_GAME_STARTR             = 0x1A,
    SND_GENRL_FRONTEND_GAME_WEAPONL            = 0x1B,
    SND_GENRL_FRONTEND_GAME_WEAPONR            = 0x1C,
    SND_GENRL_FRONTEND_GAME_WIND_L             = 0x1D,
    SND_GENRL_FRONTEND_GAME_WIND_R             = 0x1E,
};

enum SND_GENRL_FRONTEND_MENU : eSoundID {
    SND_GENRL_FRONTEND_MENU_BACKL      = 0x0,
    SND_GENRL_FRONTEND_MENU_BACKR      = 0x1,
    SND_GENRL_FRONTEND_MENU_ERRORL     = 0x2,
    SND_GENRL_FRONTEND_MENU_ERRORR     = 0x3,
    SND_GENRL_FRONTEND_MENU_HIGHLIGHTL = 0x4,
    SND_GENRL_FRONTEND_MENU_HIGHLIGHTR = 0x5,
    SND_GENRL_FRONTEND_MENU_SELECTL    = 0x6,
    SND_GENRL_FRONTEND_MENU_SELECTR    = 0x7,
    SND_GENRL_FRONTEND_MENU_VOLTEST    = 0x8,
};

enum  SND_GENRL_RAIN : eSoundID {
    SND_GENRL_RAIN_RAINLONG  = 0x0,
    SND_GENRL_RAIN_RAINSHORT = 0x1,
    SND_GENRL_RAIN_DROP01    = 0x2,
    SND_GENRL_RAIN_DROP02    = 0x3,
    SND_GENRL_RAIN_DROP03    = 0x4,
    SND_GENRL_RAIN_DROP04    = 0x5,
    SND_GENRL_RAIN_DROP05    = 0x6,
    SND_GENRL_RAIN_DROP06    = 0x7,
    SND_GENRL_RAIN_DROP07    = 0x8,
    SND_GENRL_RAIN_DROP08    = 0x9,
    SND_GENRL_RAIN_DROP09    = 0xA,
    SND_GENRL_RAIN_DROP10    = 0xB,
    SND_GENRL_RAIN_RAINCAR01 = 0xC,
    SND_GENRL_RAIN_RAINCAR02 = 0xD,
    SND_GENRL_RAIN_RAINCAR03 = 0xE,
    SND_GENRL_RAIN_RAINCAR04 = 0xF,
};

enum SND_GENRL_SWIMMING : eSoundID {
    SND_GENRL_SWIMMING_SWIM1 = 0x0,
    SND_GENRL_SWIMMING_SWIM2 = 0x1,
    SND_GENRL_SWIMMING_SWIM3 = 0x2,
    SND_GENRL_SWIMMING_SWIM4 = 0x3,
    SND_GENRL_SWIMMING_SWIM5 = 0x4,
};

//
// Vehicle sounds
// - P = Player
// - D = Dummy
//

enum SND_GENRL_CRANE_P : eSoundID {
    SND_GENRL_CRANE_P_CRANE_ENGINE  = 0x0,
    SND_GENRL_CRANE_P_LIFT_LOOP     = 0x1,
    SND_GENRL_CRANE_P_CRANE_LIMIT   = 0x2,
    SND_GENRL_CRANE_P_CRANE_OFF     = 0x3,
    SND_GENRL_CRANE_P_MAGNET_ATTACH = 0x4,
};

enum SND_GENRL_HARVESTER_P : eSoundID {
    SND_GENRL_HARVESTER_P_HAR_AC         = 0x0,
    SND_GENRL_HARVESTER_P_HAR_TCRZ       = 0x1,
    SND_GENRL_HARVESTER_P_ZHAR_OFF       = 0x2,
    SND_GENRL_HARVESTER_P_ZZHARVEST_LOOP = 0x3,
    SND_GENRL_HARVESTER_P_ZZHARVEST_PED  = 0x4,
};


enum SND_GENRL_APACHE_D : eSoundID {
    SND_GENRL_APACHE_D_APACHEDISTANT = 0x0,
    SND_GENRL_APACHE_D_APACHEDUMMY   = 0x1,
};

enum SND_GENRL_SINGLEPROP : eSoundID {
    SND_GENRL_SINGLEPROP_SINGLEPROPFRONT = 0x0,
    SND_GENRL_SINGLEPROP_SINGLEPROPREAR  = 0x1,
};

enum SND_GENRL_BICYCLE_D : eSoundID {
    SND_GENRL_BICYCLE_D_BICYCLE_TYRE_LOOP  = 0x0,
    SND_GENRL_BICYCLE_D_SPROCKET_LOOP_SLOW = 0x1,
};

enum SND_GENRL_ICEVAN_P : eSoundID {
    SND_GENRL_ICEVAN_P_ICE_AC     = 0x0,
    SND_GENRL_ICEVAN_P_ICE_TCRZ   = 0x1,
    SND_GENRL_ICEVAN_P_ZICE_OFF   = 0x2,
    SND_GENRL_ICEVAN_P_ZZICE_TUNE = 0x3,
};

enum SND_GENRL_TRAIN_P : eSoundID {
    SND_GENRL_TRAIN_P_TRAIN_BRAKES_A    = 0x0,
    SND_GENRL_TRAIN_P_TRAIN_BRAKES_B    = 0x1,
    SND_GENRL_TRAIN_P_TRAIN_ENGINE_FAST = 0x2,
    SND_GENRL_TRAIN_P_TRAIN_ENGINE_SLOW = 0x3,
    SND_GENRL_TRAIN_P_TRAIN_TRACK       = 0x4,
    SND_GENRL_TRAIN_P_TRACK_JOIN_1      = 0x5,
    SND_GENRL_TRAIN_P_TRACK_JOIN_2      = 0x6,
    SND_GENRL_TRAIN_P_TRACK_JOIN_3      = 0x7,
    SND_GENRL_TRAIN_P_TRACK_JOIN_4      = 0x8,
    SND_GENRL_TRAIN_P_TRACK_JOIN_5      = 0x9,
};

enum SND_GENRL_TRAIN_D : eSoundID {
    SND_GENRL_TRAIN_D_TRAIN_ENGINE_SLOW = 0x0,
    SND_GENRL_TRAIN_D_TRAIN_HORN        = 0x1,
    SND_GENRL_TRAIN_D_TRAIN_TRACK       = 0x2,
    SND_GENRL_TRAIN_D_TRACK_JOIN_3      = 0x3,
    SND_GENRL_TRAIN_D_TRACK_JOIN_4      = 0x4,
    SND_GENRL_TRAIN_D_TRACK_JOIN_5      = 0x5,
};

enum SND_GENRL_RC_PLANE_D : eSoundID {
    SND_GENRL_RC_PLANE_D_RC_PLANE_REV = 0x0,
};

enum SND_GENRL_RC_HELI_D : eSoundID {
    SND_GENRL_RC_HELI_D_RC_HELI_REV = 0x0,
};

enum SND_GENRL_HOVERCRAFT_D : eSoundID {
    SND_GENRL_HOVERCRAFT_D_HOV_CRZ = 0x0,
    SND_GENRL_HOVERCRAFT_D_HOV_ID  = 0x1,
};

enum SND_GENRL_GOLF_D : eSoundID {
    SND_GENRL_GOLF_D_GOL_CRZ = 0x0,
    SND_GENRL_GOLF_D_GOL_ID  = 0x1,
};

enum SND_GENRL_FORKLIFT_D : eSoundID {
    SND_GENRL_FORKLIFT_D_FOR_CRZ  = 0x0,
    SND_GENRL_FORKLIFT_D_FOR_ID   = 0x1,
    SND_GENRL_FORKLIFT_D_FOR_LIFT = 0x2,
};

enum SND_GENRL_CHAINSAW_P : eSoundID {
    SND_GENRL_CHAINSAW_P_SAW_CRZ = 0x0,
    SND_GENRL_CHAINSAW_P_SAW_ID  = 0x1,
    SND_GENRL_CHAINSAW_P_SAW_OFF = 0x2,
};
