name: Build

env:
  # Compile in parallel where possible.
  CL: /MP

  # Path to the CMake build directory.
  build: "${{ github.workspace }}/build"

# Triggers the workflow on push or pull request events for all branches.
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025-vs2026]
        arch: [x86]
        conf: [Debug, Release]
        unity: [Unity, NoUnity]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup and build project using Conan
        uses: ./.github/actions/conan
        with:
          arch: ${{ matrix.arch }}
          conf: ${{ matrix.conf }}
          unity_build: ${{ matrix.unity == 'Unity' && 'true' || 'false' }}
          build: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: gta_reversed-${{ matrix.conf }}-${{ matrix.unity }}
          path: bin/${{ matrix.conf }}
